Dev
hirwaaldo1/Ojemba-Assessment-With-js pull request #1
Opened 2023-05-17 10:04 UTC by hirwaaldo1

2023-05-18 06:52 UTC, mhenriette requested changes
Your code looks good, you can make minor requested changes to make it better.

2023-05-18 06:52 UTC, mhenriette commented on src/passwordValidation.js
> +  if (password.length !== 10) {
There is no need to add curly braces here; it can be written in one line of code.

2023-05-18 06:52 UTC, mhenriette commented on src/passwordValidation.js
> +  if (!/[a-zA-Z]/.test(password)) {
same here, This can be applied to all the 'if' conditions that return only one line of code.

2023-05-18 07:17 UTC, hirwaaldo1 reviewed
fix: remove backtes in if condition

2023-05-18 07:55 UTC, mhenriette approved these changes
Looks good 👍🏽

2023-05-18 08:13 UTC, arjorb approved these changes
LGTM 🚀

2023-05-23 08:09 UTC, mhenriette approved these changes
Looks good 👍🏽

2023-05-23 10:43 UTC, arjorb commented on src/passwordPenalty.js
> +  const findDublpsLetter = password.match(/(\w)\1+/);
If possible can you try to write descriptive naming for example it's hard to know what Dublps mean

2023-05-23 11:01 UTC, arjorb approved these changes
Looks good 🚀

2023-06-05 20:48 UTC, merged